import ProjectAxiomAudit

import ModelStatements
import NormalKernelIdentity

import UniformModelExample
import ModelLawTransport

import PlanarModelTheorem
import RealModelTheorem
import RealConditionalKernel

import MatrixColumnBound
import PlanarNets

#print axioms HighBandLSV.eventually_high_band_lsv
#print axioms HighBandLSV.eventually_actual_numerics
#print axioms HighBandLSV.Planar.sum_has_bounded_density
#print axioms HighBandLSV.Planar.sum_small_ball
#print axioms HighBandLSV.dimension_loss_normal_union
#print axioms HighBandLSV.dimension_loss_final_gap
#print axioms HighBandLSV.PlanarBandModel.selected_rows_small_ball
#print axioms HighBandLSV.PlanarBandModel.finite_net_small_ball
#print axioms HighBandLSV.ColumnExposure.expose_preserving
#print axioms HighBandLSV.ColumnExposure.moving_block_small_ball
#print axioms HighBandLSV.NormalEvents.measurableSet_good
#print axioms HighBandLSV.NormalEvents.exists_unit_normal
#print axioms HighBandLSV.PlanarBandModel.column_distance_small_ball
#print axioms HighBandLSV.PlanarNets.exists_annular_net

#check HighBandLSV.eventually_planar_band_lsv
#check HighBandLSV.eventually_real_band_lsv
#print axioms HighBandLSV.eventually_planar_band_lsv
#print axioms HighBandLSV.eventually_real_band_lsv
#print axioms HighBandLSV.RealColumnExposure.conditional_jointLaw
#print axioms HighBandLSV.real_bad_normals_from_numerics
#print axioms HighBandLSV.Examples.model_nonempty
#print axioms HighBandLSV.Examples.eventually_uniform_dense_lsv
#print axioms HighBandLSV.ModelLawTransport.real_matrix_law
#print axioms HighBandLSV.ModelLawTransport.planar_matrix_law
#check HighBandLSV.ModelStatements.real_main_statement
#check HighBandLSV.ModelStatements.planar_main_statement
#print axioms HighBandLSV.ModelStatements.real_main_statement
#print axioms HighBandLSV.ModelStatements.planar_main_statement
#print axioms HighBandLSV.NormalKernelIdentity.isNormal_iff_ker
