import PlanarModelTheorem

import RealTensorization
import RealNormalNetEvents
import RealRawBound
import ModelNumerics
import FiniteProbability

import RadialLedger
import AnisotropicMesh
#print prefix HighBandLSV.RadialLedger
#check HighBandLSV.Anisotropic.actual_endpoint_ratio
#check HighBandLSV.Anisotropic.System.center_card
#check HighBandLSV.Anisotropic.labelWeight_pos
#check HighBandLSV.Anisotropic.labelWeight_le_one
#check HighBandLSV.RealTensorization.center_union_probability
#check HighBandLSV.RealTensorization.rowProduct
#check HighBandLSV.RealNormalNetEvents.fixedBad_subset_net_union
#check HighBandLSV.RealNormalNetEvents.endpoint_labels_card
#check HighBandLSV.RealRawBound.actual_fixedEnvelope_le_raw
#check HighBandLSV.BlockGeometry.Partition.sum_card_blocks
#check HighBandLSV.ModelNumerics.certificate_dimension_loss_union
#check HighBandLSV.FiniteProbability.finite_union_bound
#check HighBandLSV.planar_bad_normals_from_numerics
#check HighBandLSV.planar_model_lsv_of_numerics
#check HighBandLSV.eventually_planar_band_lsv
#print prefix HighBandLSV.FiniteProbability
#check HighBandLSV.certificate_dimension_loss_union
#check HighBandLSV.ModelPartition.actual
#check HighBandLSV.RadialRawBound.actual_fixedEnvelope_le_raw
#check HighBandLSV.FixedNormalProbability.fixed_probability
