import RealTensorization
import RealNormalNetEvents
import RealRawBound
import ModelNumerics
import FiniteProbability

import RadialLedger
import AnisotropicMesh
#print prefix HighBandLSV.RadialLedger
#check HighBandLSV.Anisotropic.actual_endpoint_ratio
#check HighBandLSV.Anisotropic.System.center_card
#check HighBandLSV.Anisotropic.labelWeight_pos
#check HighBandLSV.Anisotropic.labelWeight_le_one
#check HighBandLSV.RealTensorization.center_union_probability
#check HighBandLSV.RealTensorization.rowProduct
#check HighBandLSV.RealNormalNetEvents.fixedBad_subset_net_union
#check HighBandLSV.RealNormalNetEvents.endpoint_labels_card
#check HighBandLSV.RealRawBound.actual_fixedEnvelope_le_raw
#check HighBandLSV.BlockGeometry.Partition.sum_card_blocks
#check HighBandLSV.ModelNumerics.certificate_dimension_loss_union
#check HighBandLSV.FiniteProbability.finite_union_bound
