import PlanarModelTheorem

import RealNormalNetEvents
import RealRawBound
import ModelNumerics
import FiniteProbability

import RadialLedger
import AnisotropicMesh
#print prefix HighBandLSV.RadialLedger
#check HighBandLSV.Anisotropic.actual_endpoint_ratio
#check HighBandLSV.Anisotropic.System.center_card
#check HighBandLSV.RealNormalNetEvents.fixedBad_subset_net_union
#check HighBandLSV.RealNormalNetEvents.endpoint_labels_card
#check HighBandLSV.RealRawBound.actual_fixedEnvelope_le_raw
#check HighBandLSV.BlockGeometry.Partition.sum_card_blocks
#check HighBandLSV.planar_bad_normals_from_numerics
#check HighBandLSV.planar_model_lsv_of_numerics
#check HighBandLSV.eventually_planar_band_lsv
#print prefix HighBandLSV.FiniteProbability
#check HighBandLSV.certificate_dimension_loss_union
#check HighBandLSV.ModelPartition.actual
#check HighBandLSV.RadialRawBound.actual_fixedEnvelope_le_raw
#check HighBandLSV.MeshParameters.actual_mesh_bounds
#check HighBandLSV.Anisotropic.actual_mesh_quarter
#check HighBandLSV.eventually_model_numerics
#check HighBandLSV.ModelPartition.retained_rows_fit
#check HighBandLSV.ModelPartition.local_band
#check HighBandLSV.ModelPartition.columnBlock
#check HighBandLSV.ModelPartition.columnBlock_local
#check HighBandLSV.dimension_loss_column_union_bound
#check HighBandLSV.MatrixGeometry.hs_cutoff_column_bound
